title: Jimmy Atterholt
logo: /assets/img/headshot_website.jpg
description: Me admiring Moro Rock, Sequoia NP
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-tabs
