title: James Atterholt
logo: /assets/img/logo.png
description: PhD student in geophysics at Caltech
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
