title: Jimmy Atterholt
logo: /assets/img/CascadiaMargin.jpg
description: Me and Bento at the Cascadia margin
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-tabs
