title: Jimmy Atterholt
logo: /assets/img/headshot_website.jpg
description: See my research blog and CV below
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-tabs
